title: 5Greplay
email: contact@montimage.com
description: >-
  5Greplay is a tool for modifying and replaying 5G protocol network traffic in realtime

baseurl: "/"
url: "https://5greplay.org"
author: "Montimage EURL"
github_username: montimage
_google_analytics: UA-NNNNNNNN-N
_safe: true

theme: minima

# Build settings
markdown: kramdown

header_pages:
  - docs.md
  - about.md
  - github.md

show_excerpts: true

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: post
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      layout: post

_plugins:
  - jekyll-coffeescript
  - jekyll-commonmark-ghpages
  - jekyll-gist
  #- jekyll-github-metadata
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from
