title: 5Greplay
email: contact@montimage.com
description: >-
  5Greplay is a tool for modifying and replaying 5G protocol network traffic in realtime

baseurl: "/"
url: "https://5greplay.org"
author: "Montimage EURL"
github_username: montimage
_google_analytics: UA-NNNNNNNN-N

theme: minima

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from

header_pages:
  - _docs/readme.md
  - about.md
  - github.md

show_excerpts: true

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path/

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: page
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      layout: post

# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/