name: C/C++ CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: setup environment
      run: |
         sudo apt update && sudo apt-get install libxml2-dev liblzma-dev libicu-dev libpcap-dev libconfuse-dev libsctp-dev gcc make
         sudo dpkg -i lib/mmt-dpi*.deb && sudo ldconfig
    - name: make
      run: make 
    - name: make static
      run: make STATIC_LINK=1 VERBOSE=1
    - name: compile sample rules
      run: make sample-rules
